### ISSUE TITLE
Primeng

### ISSUE THREAD

**Issue by haoguanjun** [haoguanjun/jekyll#9]
https://haoguanjun.github.io/jekyll/2017/08/25/primeng.html

**Comment by zzunstu** [comment]
you are an expert in many fields. [thumbup]

**Comment by zzunstu** [comment]
正在做站内搜索吗？

**Comment by zzunstu** [comment]
怎么艾特一个人？

**Comment by zzunstu** [comment]
@作者，怎么不回复我？ [大哭] (╯︵╰)

**Comment by haoguanjun** [comment]
what's up?

**Comment by zzunstu** [comment]
老师，发现了一个Bug，posts分页的“前一页”不work。

**Comment by haoguanjun** [comment]
mark

**Comment by haoguanjun** [comment]
修好了，多写了一个 href=

**Comment by haoguanjun** [comment]
https://github.com/haoguanjun/jekyll/commit/4a48afb83ebee82c703ddf0590a56c26ccbfe998

**Comment by zzunstu** [comment]
@haoguanjun  Good!
